export const defaultGreenhouseCompanies = [
  { name: "OpenAI", website: "https://openai.com", greenhouse_slug: "openai", industry: "AI" },
  { name: "Anthropic", website: "https://anthropic.com", greenhouse_slug: "anthropic", industry: "AI" },
  { name: "Figma", website: "https://figma.com", greenhouse_slug: "figma", industry: "Design software" },
  { name: "Notion", website: "https://notion.so", greenhouse_slug: "notion", industry: "Productivity software" },
  { name: "Stripe", website: "https://stripe.com", greenhouse_slug: "stripe", industry: "Payments" },
  { name: "Ramp", website: "https://ramp.com", greenhouse_slug: "ramp", industry: "Fintech" },
  { name: "Rippling", website: "https://rippling.com", greenhouse_slug: "rippling", industry: "HR software" },
  { name: "Plaid", website: "https://plaid.com", greenhouse_slug: "plaid", industry: "Fintech" },
  { name: "Brex", website: "https://brex.com", greenhouse_slug: "brex", industry: "Fintech" },
  { name: "Vercel", website: "https://vercel.com", greenhouse_slug: "vercel", industry: "Developer tools" },
  { name: "Linear", website: "https://linear.app", greenhouse_slug: "linear", industry: "Developer tools" },
  { name: "Scale AI", website: "https://scale.com", greenhouse_slug: "scaleai", industry: "AI" },
  { name: "Datadog", website: "https://datadoghq.com", greenhouse_slug: "datadog", industry: "Observability" },
  { name: "Discord", website: "https://discord.com", greenhouse_slug: "discord", industry: "Communications" },
  { name: "Asana", website: "https://asana.com", greenhouse_slug: "asana", industry: "Productivity software" },
  { name: "Calendly", website: "https://calendly.com", greenhouse_slug: "calendly", industry: "Productivity software" },
  { name: "Zapier", website: "https://zapier.com", greenhouse_slug: "zapier", industry: "Automation" },
  { name: "Webflow", website: "https://webflow.com", greenhouse_slug: "webflow", industry: "Web software" },
  { name: "Algolia", website: "https://algolia.com", greenhouse_slug: "algolia", industry: "Search" },
  { name: "Sentry", website: "https://sentry.io", greenhouse_slug: "sentry", industry: "Developer tools" },
  { name: "Cloudflare", website: "https://cloudflare.com", greenhouse_slug: "cloudflare", industry: "Infrastructure" },
  { name: "DoorDash", website: "https://doordash.com", greenhouse_slug: "doordash", industry: "Marketplace" },
  { name: "HashiCorp", website: "https://hashicorp.com", greenhouse_slug: "hashicorp", industry: "Infrastructure" },
  { name: "MongoDB", website: "https://mongodb.com", greenhouse_slug: "mongodb", industry: "Database" },
  { name: "Hugging Face", website: "https://huggingface.co", greenhouse_slug: "huggingface", industry: "AI" }
];
