export type DefaultAshbySource = {
  industry: string;
  name: string;
  slug: string;
};

export const defaultAshbySources = [
  { name: "OpenAI", slug: "openai", industry: "AI" },
  { name: "Perplexity", slug: "perplexity", industry: "AI search" },
  { name: "Cursor", slug: "cursor", industry: "AI developer tools" },
  { name: "Harvey", slug: "harvey", industry: "Legal AI" },
  { name: "ElevenLabs", slug: "elevenlabs", industry: "Voice AI" },
  { name: "Sierra", slug: "sierra", industry: "AI customer experience" },
  { name: "Cohere", slug: "cohere", industry: "AI" },
  { name: "Cognition", slug: "cognition", industry: "AI developer tools" },
  { name: "LangChain", slug: "langchain", industry: "AI developer tools" },
  { name: "Baseten", slug: "baseten", industry: "AI infrastructure" },
  { name: "Modal", slug: "modal", industry: "AI infrastructure" },
  { name: "Cartesia", slug: "cartesia", industry: "Voice AI" },
  { name: "Decagon", slug: "decagon", industry: "AI customer support" },
  { name: "Exa", slug: "exa", industry: "AI search" },
  { name: "Factory", slug: "factory", industry: "AI developer tools" },
  { name: "Granola", slug: "granola", industry: "AI productivity" },
  { name: "Lovable", slug: "lovable", industry: "AI developer tools" },
  { name: "Nomic", slug: "nomic", industry: "AI infrastructure" },
  { name: "OpenEvidence", slug: "openevidence", industry: "Healthcare AI" },
  { name: "Runway", slug: "runway", industry: "Generative AI" },
  { name: "Unstructured", slug: "unstructured", industry: "AI data" },
  { name: "Vapi", slug: "vapi", industry: "Voice AI" },
  { name: "Bland", slug: "bland", industry: "Voice AI" },
  { name: "Braintrust", slug: "braintrust", industry: "AI evaluation" },
  { name: "Deepgram", slug: "deepgram", industry: "Voice AI" },
  { name: "Retell AI", slug: "retell-ai", industry: "Voice AI" },
  { name: "Browserbase", slug: "browserbase", industry: "AI browser infrastructure" },
  { name: "Character AI", slug: "character", industry: "AI" },
  { name: "Pika", slug: "pika", industry: "Generative video" },
  { name: "Midjourney", slug: "midjourney", industry: "Generative AI" },
  { name: "Suno", slug: "suno", industry: "Generative audio" },
  { name: "Rime", slug: "rime", industry: "Voice AI" },
  { name: "Loop", slug: "loop-earplugs", industry: "Consumer technology" },
  { name: "Linear", slug: "linear", industry: "Productivity software" },
  { name: "Replit", slug: "replit", industry: "Developer tools" },
  { name: "Neon", slug: "neon", industry: "Database" },
  { name: "Clerk", slug: "clerk", industry: "Authentication" },
  { name: "Resend", slug: "resend", industry: "Developer tools" },
  { name: "Railway", slug: "railway", industry: "Cloud infrastructure" },
  { name: "Mercury", slug: "mercury", industry: "Fintech" },
  { name: "Vanta", slug: "vanta", industry: "Security compliance" },
  { name: "Attio", slug: "attio", industry: "CRM" },
  { name: "Temporal", slug: "temporal", industry: "Developer infrastructure" },
  { name: "Airbyte", slug: "airbyte", industry: "Data infrastructure" },
  { name: "Materialize", slug: "materialize", industry: "Data infrastructure" },
  { name: "MotherDuck", slug: "motherduck", industry: "Data infrastructure" },
  { name: "Nango", slug: "nango", industry: "Developer tools" },
  { name: "Mintlify", slug: "mintlify", industry: "Developer documentation" },
  { name: "ReadMe", slug: "readme", industry: "Developer documentation" },
  { name: "Hex", slug: "hex", industry: "Data analytics" },
  { name: "Pave", slug: "pave", industry: "Compensation software" },
  { name: "Watershed", slug: "watershed", industry: "Climate software" },
  { name: "Rogo", slug: "rogo", industry: "Finance AI" },
  { name: "Astral", slug: "astral", industry: "Developer tools" },
  { name: "Airwallex", slug: "airwallex", industry: "Fintech" },
  { name: "Ramp", slug: "ramp", industry: "Fintech" },
  { name: "Plaid", slug: "plaid", industry: "Fintech" },
  { name: "Phantom", slug: "phantom", industry: "Crypto" },
  { name: "Alchemy", slug: "alchemy", industry: "Crypto infrastructure" },
  { name: "OpenSea", slug: "opensea", industry: "Crypto marketplace" },
  { name: "Dune", slug: "dune", industry: "Crypto analytics" },
  { name: "Elliptic", slug: "elliptic", industry: "Crypto compliance" },
  { name: "Blockdaemon", slug: "blockdaemon", industry: "Crypto infrastructure" },
  { name: "Paxos", slug: "paxos", industry: "Crypto infrastructure" },
  { name: "Kraken", slug: "kraken", industry: "Crypto" },
  { name: "Found", slug: "found", industry: "Fintech" },
  { name: "Levels", slug: "levels", industry: "Health technology" },
  { name: "WHOOP", slug: "whoop", industry: "Health technology" },
  { name: "Spring Health", slug: "spring-health", industry: "Health technology" },
  { name: "Hinge Health", slug: "hinge-health", industry: "Health technology" },
  { name: "Equip", slug: "equip", industry: "Health technology" },
  { name: "Grow Therapy", slug: "grow-therapy", industry: "Health technology" },
  { name: "Wayve", slug: "wayve", industry: "Autonomous driving" },
  { name: "Vercel", slug: "vercel", industry: "Developer tools" },
  { name: "Supabase", slug: "supabase", industry: "Developer tools" },
  { name: "PostHog", slug: "posthog", industry: "Product analytics" },
  { name: "Zapier", slug: "zapier", industry: "Automation" },
  { name: "Sentry", slug: "sentry", industry: "Developer tools" },
  { name: "ClickHouse", slug: "clickhouse", industry: "Database" },
  { name: "Lambda", slug: "lambda", industry: "AI infrastructure" },
  { name: "Gamma", slug: "gamma", industry: "AI productivity" },
  { name: "Amplitude", slug: "amplitude", industry: "Product analytics" },
  { name: "Loom", slug: "loom", industry: "Productivity software" },
  { name: "Mural", slug: "mural", industry: "Collaboration software" },
  { name: "Miro", slug: "miro", industry: "Collaboration software" },
  { name: "Superhuman", slug: "superhuman", industry: "Productivity software" },
  { name: "Substack", slug: "substack", industry: "Creator software" },
  { name: "Kit", slug: "kit", industry: "Creator software" },
  { name: "Ghost", slug: "ghost", industry: "Publishing software" },
  { name: "Buffer", slug: "buffer", industry: "Social media software" },
  { name: "Arcade", slug: "arcade", industry: "Product demos" },
  { name: "tldraw", slug: "tldraw", industry: "Design software" },
  { name: "lemlist", slug: "lemlist", industry: "Sales software" },
  { name: "Semgrep", slug: "semgrep", industry: "Security" },
  { name: "Socket", slug: "socket", industry: "Security" },
  { name: "Oneleet", slug: "oneleet", industry: "Security compliance" },
  { name: "Synthesia", slug: "synthesia", industry: "AI video" },
  { name: "n8n", slug: "n8n", industry: "Automation" },
  { name: "OpenRouter", slug: "openrouter", industry: "AI infrastructure" },
  { name: "Render", slug: "render", industry: "Cloud infrastructure" },
  { name: "Inngest", slug: "inngest", industry: "Developer infrastructure" },
  { name: "WorkOS", slug: "workos", industry: "Developer tools" },
  { name: "Stytch", slug: "stytch", industry: "Authentication" },
  { name: "Knock", slug: "knock", industry: "Developer tools" },
  { name: "Mux", slug: "mux", industry: "Video infrastructure" },
  { name: "Stream", slug: "stream", industry: "Developer infrastructure" },
  { name: "LiveKit", slug: "livekit", industry: "Realtime infrastructure" },
  { name: "Scribe", slug: "scribe", industry: "Productivity software" },
  { name: "Sanity", slug: "sanity", industry: "CMS" },
  { name: "Notion", slug: "notion", industry: "Productivity software" },
  { name: "Airtable", slug: "airtable", industry: "Productivity software" },
  { name: "Deel", slug: "deel", industry: "HR software" },
  { name: "Bolt", slug: "bolt", industry: "Fintech" },
  { name: "SSI", slug: "ssi", industry: "AI" },
  { name: "Wiz", slug: "wiz", industry: "Security" },
  { name: "Snyk", slug: "snyk", industry: "Security" }
] as const satisfies DefaultAshbySource[];
